### ISSUE TITLE
嘿，哥们，你还在做 Redis 的 库？

### ISSUE THREAD

**Issue by kelin-xycs** [IKende/BeetleX.Redis#1]
做一个 .Net 的 分布式缓存吧 ~！   ^^

看看我写的文章《我发起了一个 .Net Core 平台上的 分布式缓存 开源项目 ShareMemory 用于 取代 Redis》
https://www.cnblogs.com/KSongKing/p/10213051.html

**Comment by beetlex-io** [comment]
@kelin-xycs 
其实几年前已经写过了，只是基于BeetleX翻新一下放上来

**Comment by kelin-xycs** [comment]
哎？ 你现在 这个 BeetleX.Redis 不也是 Redis 的 库？

到 这个 群  384413261   里 来一起 来 玩耍   ^^

**Comment by kelin-xycs** [comment]
哦  ~~，  你到 384413261 这个 群 里 以后   @苏州 | K歌之王     就可以 找到 我了
