### ISSUE TITLE
Non disposed timer in the RedisDb class

### ISSUE THREAD

**Issue by nroypf** [IKende/BeetleX.Redis#17]
https://github.com/IKende/BeetleX.Redis/blob/9094ff58dbbc2cc62ff348187d4788b96bf65941/src/RedisDB.cs#L27

The RedisDB class instantiate a Timer (this.mDetectionTime) but do not implement IDisposable to release it.

**Comment by beetlex-io** [comment]
`RedisDb` is thread-safe and can be defined for global use of a single instance. So `RedisDb` does not provide a resource release operation at design time

**Comment by beetlex-io** [comment]
update to v0.9.7.9
