### ISSUE TITLE
ERR Protocol error: expected '$', got '*'

### ISSUE THREAD

**Issue by ray-yuruisoft** [IKende/BeetleX.Redis#2]
debris code:
string group = RedisKey.UserBag.ToString();
var key = $"{developerAppKey}{developerUserId}{deviceNo}";
return _redis.Get<UserBag>($"{group}:{key}").Result;

when i invoke 'Get' methord ,it will often thow a redis protocol err.

ERR Protocol error: expected '$', got '*'

i search many webside,but have no idear to resolve this problem.
PLZ HELP ME!

**Comment by vulegend** [comment]
I keep getting this as well. It happens on the first calls only for me

**Comment by beetlex-io** [comment]
https://github.com/beetlex-io/BeetleX.Redis/issues/19
