### ISSUE TITLE
ZRank、ZScore 等使用了Double类型，会导致小数点精度丢失。

### ISSUE THREAD

**Issue by Shikyoh** [IKende/BeetleX.Redis#28]
```C#
beetlex.CreateSequence(key).ZAdd((123.1231, "shikyoh"))

//Result:123.12309999999999
```

还有就是 ZRank 的返回结果应该为 可空类型的 double或 decimal。 如果field不存在，应该是null，不应该为 0

**Comment by beetlex-io** [comment]
估计是写入redis时，redis对这个值用了float转换引起

**Comment by Shikyoh** [comment]
如果是这样，为什么不换成Decimal类型

**Comment by beetlex-io** [comment]
ZRank 是返回排名。。。

**Comment by beetlex-io** [comment]
![image](https://user-images.githubusercontent.com/2564178/115326956-b78a0280-a1c0-11eb-99a8-2a387e7853c6.png)
具体可以跑一下组件的单元测试，有问题解决可以提个pr

**Comment by Shikyoh** [comment]
> ZRank 是返回排名。。。

ZRank的 问题是：不存在的member 返回的结果是0  。 应该为null 更合理

**Comment by Shikyoh** [comment]
![111](https://user-images.githubusercontent.com/6076516/115329994-c6bf7f00-a1c5-11eb-84c2-391e889ebe65.png)

**Comment by beetlex-io** [comment]
这个没办法的，redis存储的就是这值，可以用redis指令看一下

**Comment by Shikyoh** [comment]
> 这个没办法的，redis存储的就是这值，可以用redis指令看一下

我用的是  beetlex.CreateSequence(key).ZAdd((123.1231, "shikyoh"))
但在  Result结果中 拿到的却是 123.12309999999999
Zadd就不应该用double类型接收

**Comment by Shikyoh** [comment]
> > 这个没办法的，redis存储的就是这值，可以用redis指令看一下
> 
> 我用的是 beetlex.CreateSequence(key).ZAdd((123.1231, "shikyoh"))
> 但在 Result结果中 拿到的却是 123.12309999999999
> Zadd就不应该用double类型接收

精度丢失的问题，不是double类型的问题。  但最好还是修改下 ZRank 和ZScore  不存在的field 返回0 的问题。
