### ISSUE TITLE
关于默认值的疑问

### ISSUE THREAD

**Issue by nodyang** [IKende/BeetleX.Redis#34]
![image](https://user-images.githubusercontent.com/3090191/162623845-d8f4ae76-bad1-4128-a92d-76102b1c2fae.png)
希望是得到默认值 而不是异常

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/162624013-95b3db77-1275-42fc-a4e6-d3b75fb3c23d.png)

**Comment by beetlex-io** [comment]
在设计的时候没考虑用于值类型，这个是要调整一下

**Comment by beetlex-io** [comment]
更新版本1.4.3.1803

**Comment by nodyang** [comment]
> 更新版本1.4.3.1803

漂亮。。
