### ISSUE TITLE
Incrby 应该支持long

### ISSUE THREAD

**Issue by nodyang** [IKende/BeetleX.Redis#35]
![image](https://user-images.githubusercontent.com/3090191/162687310-2be2d850-3522-4e0f-95cf-7faaaad28185.png)
![image](https://user-images.githubusercontent.com/3090191/162687458-edabf299-46f8-4fc0-a838-9bc2c8df6dd7.png)

我们在升级老系统。以前的csredis  都是long  可能需要改下。。

**Comment by nodyang** [comment]
还有一些小小小的建议 
![image](https://user-images.githubusercontent.com/3090191/162703329-70730f53-331e-4e09-84cb-2d5fe976ad5a.png)
![image](https://user-images.githubusercontent.com/3090191/162703386-7bb686d1-e655-4732-9578-bc8d9491c4f0.png)
如果是空的集合。好像也报错。虽然可以通过数量去判断下。

**Comment by beetlex-io** [comment]
更新[1.4.4.1803]

**Comment by nodyang** [comment]
> 更新[1.4.4.1803]

good 3Q
