### ISSUE TITLE
关于部分客户端会报错:"exceeding maximum number of connections"的问题

### ISSUE THREAD

**Issue by linqingfeng** [IKende/BeetleX.Redis#4]
您好，

我部署了大概十来个客户端，运行一段时间后，有一两个就一直报错：

`BeetleX.Redis.RedisException: exceeding maximum number of connections
   at BeetleX.Redis.RedisList1.Push(T[] values)`

但是我检查过redis服务端的设置，远没有超过连接数

*.*.*.*:6379> info clients
\# Clients
connected_clients:247
client_longest_output_list:0
client_biggest_input_buf:40507
blocked_clients:0
(1.50s)
*.*.*.*:6379> CONFIG GET maxclients
1) "maxclients"
2) "60000"

部署环境：
ubuntu 18.04
.net core 2.1
redis_version:4.0.9

请问会是什么原因？谢谢！

**Comment by beetlex-io** [comment]
RedisHost 有属性设置，默认30

**Comment by linqingfeng** [comment]
哦，看到了，万分感谢 \(^o^)/~

public int MaxConnections { get; set; } = 30;
