### ISSUE TITLE
Redis connection string with SSL,how to connection using  BeetleX.Redis

### ISSUE THREAD

**Issue by dapengweb** [IKende/BeetleX.Redis#5]
Redis connection string with SSL,how to connection using  BeetleX.Redis
As fllows:bixx.redis.cache.chinacloudapi.cn:6780,password=67IPZSX9xxxxbAl3kOpwkk=,ssl=True,abortConnect=False

**Comment by beetlex-io** [comment]
This version not support ssl
set password
``` csharp
RedisDB DB = new RedisDB(0)
DB.Host.AddWriteHost("bixx.redis.cache.chinacloudapi.cn",6780).Password="123456"
```

**Comment by dapengweb** [comment]
> This version not support ssl
> set password
> 
> ```cs
> RedisDB DB = new RedisDB(0)
> DB.Host.AddWriteHost("bixx.redis.cache.chinacloudapi.cn",6780).Password="123456"
> ```

When will it be supported ？thanks

**Comment by beetlex-io** [comment]
I need a redis service running on SSL to test

**Comment by beetlex-io** [comment]
update to 0.8.0
